version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgresql"
      POSTGRES_USER: "netology"
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgres
